# Generated by Django 4.1 on 2022-09-06 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PreCadastroImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('quadra', models.CharField(max_length=3)),
                ('lote', models.CharField(max_length=3)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('medicao', models.CharField(blank=True, max_length=10)),
                ('cartorio', models.CharField(blank=True, max_length=10)),
                ('conferido', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('I', 'Iniciado'), ('E', 'Enviado para cartorio'), ('M', 'Medição'), ('S', 'Suspenso'), ('A', 'Arquivado'), ('G', 'Aguardando registro'), ('R', 'Registrado')], default='I', max_length=1)),
                ('observacao', models.TextField(blank=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.bairro')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.cadastropessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Conjuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conj', models.CharField(max_length=255)),
                ('cpf_conj', models.CharField(max_length=14, unique=True)),
                ('rg_conj', models.CharField(max_length=30)),
                ('orgao_rg_conj', models.CharField(max_length=10)),
                ('estado_rg_conj', models.CharField(max_length=2)),
                ('nome_pai_conj', models.CharField(max_length=255)),
                ('nome_mae_conj', models.CharField(max_length=255)),
                ('profissao_conj', models.CharField(max_length=50)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.cadastropessoa')),
            ],
        ),
    ]
