# Generated by Django 4.1 on 2022-09-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_bairro_precadastroimovel_conjuge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjuge',
            old_name='cpf_conj',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='estado_rg_conj',
            new_name='estado_rg',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='nome_conj',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='nome_mae_conj',
            new_name='nome_mae',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='nome_pai_conj',
            new_name='nome_pai',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='orgao_rg_conj',
            new_name='orgao_rg',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='profissao_conj',
            new_name='profissao',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='rg_conj',
            new_name='rg',
        ),
    ]
