# Generated by Django 4.1 on 2022-09-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_rename_cpf_conj_conjuge_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastroimovel',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
