# Generated by Django 4.1 on 2022-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_precadastroimovel_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='bairro',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
