# Generated by Django 4.1 on 2022-09-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_bairro_bairro_alter_precadastroimovel_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuge',
            name='titular',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.cadastropessoa'),
        ),
    ]
