# Generated by Django 4.1 on 2022-09-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_conjuge_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastroimovel',
            name='proprietario',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.cadastropessoa'),
        ),
    ]
