# Generated by Django 4.1 on 2022-09-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_precadastroimovel_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuge',
            name='titular',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastropessoa'),
        ),
        migrations.AlterField(
            model_name='precadastroimovel',
            name='proprietario',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastropessoa'),
        ),
    ]
