# Generated by Django 4.1 on 2022-09-27 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_conjuge_titular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuge',
            name='titular',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastropessoa'),
        ),
        migrations.AlterField(
            model_name='precadastroimovel',
            name='proprietario',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastropessoa'),
        ),
    ]
