# Generated by Django 4.1 on 2022-09-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_conjuge_titular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjuge',
            old_name='nome',
            new_name='nome_conj',
        ),
    ]
