# Generated by Django 4.1 on 2022-09-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_rename_nome_conjuge_nome_conj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjuge',
            old_name='cpf',
            new_name='cpf_conj',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='estado_rg',
            new_name='estado_rg_conj',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='nome_mae',
            new_name='nome_mae_conj',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='nome_pai',
            new_name='nome_pai_conj',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='orgao_rg',
            new_name='orgao_rg_conj',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='profissao',
            new_name='profissao_conj',
        ),
        migrations.RenameField(
            model_name='conjuge',
            old_name='rg',
            new_name='rg_conj',
        ),
    ]
