# Generated by Django 4.1 on 2022-09-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_rename_cpf_conjuge_cpf_conj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuge',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastropessoa'),
        ),
    ]
