# Generated by Django 4.1 on 2022-09-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_alter_conjuge_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastroimovel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastropessoa'),
        ),
    ]
