# Generated by Django 4.1 on 2022-10-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0016_alter_precadastroimovel_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastroimovel',
            name='usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastropessoa',
            name='profissao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastropessoa',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='conjuge',
            name='profissao_conj',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='precadastroimovel',
            name='status',
            field=models.CharField(choices=[('I', 'Iniciado'), ('E', 'Enviado para cartorio'), ('M', 'Medição'), ('S', 'Suspenso'), ('A', 'Arquivado'), ('P', 'Pendente'), ('G', 'Aguardando registro'), ('R', 'Registrado')], default='I', max_length=1),
        ),
    ]
