# Generated by Django 4.1 on 2022-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_precadastroimovel_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastroimovel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
